title: Pablo Sebasti치n Jerez Agurto # your name (or website title) here
logo: "/images/1665372502474.jfif?raw=true" # your photo (or logo) here
description: > 

  Ingeniero Civil Industrial, Universidad de Concepci칩n
  <br>
  24 a침os
  <br>
  Concepci칩n, Chile
  <br><br>
  Contacto:
  <br>
  <a href="https://www.linkedin.com/in/pablo-jerez-agurto-2551821ab/">Linkedin</a> 
  <br>
  <a href="https://github.com/Pjerez98">Github</a> 
  <br>
  <a href="/pdf/Pablo_Jerez_CV_.pdf">Curriculum Vitae (CV) </a> 
  <br>
  <a href="mailto:pabloj98.jerez@gmail.com">pabloj98.jerez@gmail.com </a> 
  <br>
  <a href="tel:+56952302919">+56952302919 </a> 

  <!---<a href="/pdf/MT_Pablo_Jerez_FINAL.pdf">Revisa mi Tesis de Pregrado </a>--->
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
